CREATE TABLE IF NOT EXISTS users (
	id INT(256) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS projects (
	id INT(256) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
	id INT(256) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	description TEXT,
	user_id INT(10) UNSIGNED NOT NULL,
	project_id INT(256) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS user_projects (
	project_id INT(256) UNSIGNED NOT NULL,
	user_id INT(256) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS assigned_users (
	task_id INT(256) UNSIGNED NOT NULL,
	user_id INT(256) UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
	id INT(256) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	path VARCHAR(255) NOT NULL,
	project_id INT(256) DEFAULT NULL,
	task_id INT(256) DEFAULT NULL
